package org.example;

public enum TokenClass {
    IDENTIFIER, INTEGER, FLOAT, KEYWORD, INVALID, ASSIGNMENT_OPERATOR, SEMICOLON,
    ARITHMETIC_OPERATOR, COMPARISON_OPERATOR, SPECIAL_CHARACTER

}

/*
 PLUS,MINUS,
 TIMES,DIVIDE, LEFT_PARENTHESIS, RIGHT_PARENTHESIS,COMMA, DOT, DOTDOT, COLON, EQUAL,
 LOWER_OR_EQUALS, GREATER_OR_EQUALS, NOT_EQUALS, GREATER_THAN, LOWER_THAN,
 AT_SIGN, LEFT_BRACE, RIGHT_BRACE

 */